dateModified: 1734602172
email:
  fromEmail: ggreenaway053@gmail.com
  fromName: 'Eyekiller / CancerFocusNI'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    d905f5ea-6302-42ff-a1ea-807c75c36f08: 'Eyekiller / CancerFocusNI' # Eyekiller / CancerFocusNI
    e71aaf2e-494c-46b2-acab-a0170ac6c1f6: 'Eyekiller / CancerFocusNI' # Eyekiller / CancerFocusNI
system:
  edition: solo
  live: true
  name: 'Eyekiller / CancerFocusNI'
  schemaVersion: 5.5.0.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
