dateModified: 1734602572
email:
  fromEmail: ggreenaway053@gmail.com
  fromName: 'Eyekiller / Dev Test'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    7a46afc5-f9f9-4a1e-bb22-5540164a19db: 'Eyekiller / Dev Test' # Eyekiller / Dev Test
    a172bc91-b43a-49c8-8303-5d07b3a386b9: 'Eyekiller / Dev Test' # Eyekiller / Dev Test
system:
  edition: solo
  live: true
  name: 'Eyekiller / Dev Test'
  schemaVersion: 5.5.0.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
